### ISSUE TITLE
Spotify ne se lance pas

### ISSUE THREAD

**Issue by arnoakavdb** [NextDom/plugin-AndroidRemoteControl#45]
## Etapes a reproduire (pour les bugs)
1. clic sur l'icone spotify
2.
3.
4.

## Contexte:
lorsque l'on clic sur l'icone spotify rien ne se passe
## Environnement:
* **Version**: synchro github
* **Platform**: derniere version de jeedom sur synology via debian chroot
* **Subsystem**:

**Comment by byackee** [comment]
peux tu me donner la liste de tes applis sur ton android, avec la commande 
`sudo adb -s 192.168.x.x:5555 shell "pm list packages -f" | cut -f 2 -d "="`

**Comment by arnoakavdb** [comment]
air.com.vudu.air.DownloaderTablet
air.ITVMobilePlayer
air.net.machinarium.Machinarium.GP
android
be.voo.voomotion
com.amazon.amazonvideo.livingroom.nvidia
com.android.backupconfirm
com.android.bluetooth
com.android.bluetoothmidiservice
com.android.captiveportallogin
com.android.certinstaller
com.android.cts.ctsshim
com.android.cts.priv.ctsshim
com.android.defcontainer
com.android.documentsui
com.android.dreams.basic
com.android.externalstorage
com.android.gallery3d
com.android.hotwordenrollment
com.android.htmlviewer
com.android.inputdevices
com.android.inputmethod.latin
com.android.keychain
com.android.location.fused
com.android.packageinstaller
com.android.pacprocessor
com.android.printspooler
com.android.providers.calendar
com.android.providers.contacts
com.android.providers.downloads
com.android.providers.media
com.android.providers.settings
com.android.providers.tv
com.android.providers.userdictionary
com.android.proxyhandler
com.android.sharedstoragebackup
com.android.shell
com.android.statementservice
com.android.systemui
com.android.tv.settings
com.android.vending
com.android.vpndialogs
com.android.wallpaperbackup
com.bubblesoft.android.bubbleupnp
com.bubblezapgames.supergnes_lite
com.chrome.beta
com.crunchyroll.crunchyroid
com.disney.castleofillusion_goo
com.dotemu.ddtrilogy
com.estrongs.android.pop
com.gameloft.android.ANMP.GloftA8HM
com.gameloft.android.ANMP.GloftDMHM
com.google.android.apps.inputmethod.hindi
com.google.android.apps.inputmethod.zhuyin
com.google.android.apps.mediashell
com.google.android.apps.santatracker
com.google.android.backdrop
com.google.android.backuptransport
com.google.android.ext.services
com.google.android.ext.shared
com.google.android.feedback
com.google.android.gms
com.google.android.gsf
com.google.android.gsf.notouch
com.google.android.inputmethod.japanese
com.google.android.inputmethod.korean
com.google.android.inputmethod.pinyin
com.google.android.katniss
com.google.android.leanback.ime
com.google.android.leanbacklauncher
com.google.android.leanbacklauncher.recommendations
com.google.android.marvin.talkback
com.google.android.music
com.google.android.onetimeinitializer
com.google.android.pano.packageinstaller
com.google.android.partnersetup
com.google.android.play.games
com.google.android.speech.pumpkin
com.google.android.sss
com.google.android.sss.authbridge
com.google.android.syncadapters.calendar
com.google.android.syncadapters.contacts
com.google.android.tts
com.google.android.tungsten.setupwraith
com.google.android.tv
com.google.android.tv.bugreportsender
com.google.android.tv.frameworkpackagestubs
com.google.android.tv.remote.service
com.google.android.videos
com.google.android.webview
com.google.android.youtube.tv
com.google.chromeremotedesktop
com.gotv.nflgamecenter.us.lite
com.lego.superheroes.dccomicsmightymicros
com.leosfortune
com.limelight
com.lonelycoder.mediaplayer
com.macropinch.swan
com.mvas.stb.emu.free
com.netflix.ninja
com.niklabs.pp
com.nvidia.android.webview
com.nvidia.app.messaging
com.nvidia.avsync
com.nvidia.bbciplayer
com.nvidia.bbciplayer.launch
com.nvidia.blakepairing
com.nvidia.bluetooth.ps3usbpairer
com.nvidia.bluetooth.ShieldBluetoothManager
com.nvidia.factory
com.nvidia.feedback
com.nvidia.gfn_10790111
com.nvidia.gfn_10875111
com.nvidia.gfn_1176111
com.nvidia.gfn_17400111
com.nvidia.gfn_6437111
com.nvidia.gs_100023611
com.nvidia.hdmimonitorservice
com.nvidia.hotwordsetup
com.nvidia.inputviewer
com.nvidia.irtuner
com.nvidia.KeyComboOta
com.nvidia.NvAccSt
com.nvidia.nvaudiosvc
com.nvidia.nvcecservice
com.nvidia.NvCPLSvc
com.nvidia.NvCPLUpdater
com.nvidia.nvgamecast
com.nvidia.osc
com.nvidia.ota
com.nvidia.overscancomp
com.nvidia.packagemanagerservice
com.nvidia.peripheralservice
com.nvidia.shield.hotword
com.nvidia.shield.mic
com.nvidia.shield.mic.icon
com.nvidia.shield.nas
com.nvidia.shield.nvcustomize
com.nvidia.shield.registration
com.nvidia.shield.remote.app
com.nvidia.shieldservice
com.nvidia.shieldtech.factorysyschecker
com.nvidia.shieldtech.hooks
com.nvidia.shieldtech.rpx
com.nvidia.shield.welcome
com.nvidia.stats
com.nvidia.tegraprofiler.se

**Comment by byackee** [comment]
Je ne vois pas d'appli spotify dans la liste, l'as tu bien installé?

**Comment by byackee** [comment]
Résolu
