### ISSUE TITLE
icones plex et amazon video non affichés

### ISSUE THREAD

**Issue by arnoakavdb** [NextDom/plugin-AndroidRemoteControl#46]
## Etapes a reproduire (pour les bugs)
1. 
2.
3.
4.

## Contexte:
les icônes de ces 2 applications ne s'affichent pas sur le widget du dash board
## Environnement:
* **Version**: 
* **Platform**: 
* **Subsystem**:

**Comment by byackee** [comment]
J'ai changé la méthode de recherche de l'icone.

Il faut mettre  jour le plugin pour que la modif soit effective

**Comment by byackee** [comment]
cloturé
