### ISSUE TITLE
Retour :)

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/plugin-AndroidRemoteControl#47]
Bugs :
- on/off ok mais l'icone ne passe pas rouge
- spotify marche pas
- Icone spotify moche avec fond blanc :)
Ajouter les services :
- une idée pour le off, proposer un autre off en option qui fait éteindre et non veille
- l'affichage de la résolution me semble superflu, ou alors mettre option pour le désactiver
- ajouter affichage titre appli en cours avec option affichage ou non

**Comment by byackee** [comment]
Presque tout est fait, le dernier point est impossible a faire avec adb (a ma connaissance)
