### ISSUE TITLE
Ajout de l'application TV sur TV Philips (et peut être d'autres, je ne peux pas vérifier)

### ISSUE THREAD

**Issue by rouxton** [NextDom/plugin-AndroidRemoteControl#50]
## Description

L'application TV de base n'est pas listée dans le plugin. 

## Proposition de solution (optionnel):

sudo adb shell am start org.droidtv.zapster/.playtv.activity.PlayTvActivity permet de lancer l'appli

sudo adb shell dumpsys window windows | grep -E 'mFocusedApp'| cut -d / -f 1 | cut -d " " -f 7
renvoie : org.droidtv.zapster

**Comment by slobberbone** [comment]
Salut merci pour la proposition, c'est donc l'appli TV de ta TV Philips ?
si tu fais des PR (au cas où), tu peux le faire sur la branche develop, sinon je vais regarder ça !

**Comment by rouxton** [comment]
Oui c'est bien ca. Je vais regarder pour un PR, facile pour le code principal, par contre pour la partie widget, je n'ai jamais fait, donc je laisserais cela de côté je pense. J'ai déjà testé en éditant le php à la main sur mon Jeedom (pas bien je sais :-) ) et ca me détecte bien l'appli.

**Comment by byackee** [comment]
Ok je suis entrain de faire une refonte du code pour gérer les applis avec un json plutôt que directement dans le core du plugin. Nous allons ajouter ton appli à la liste

**Comment by byackee** [comment]
J'ai completement revue le system de gestion des commandes et app, ca se fait avec du json dans le repertoire 3rdparty, plus besoin de toucher au core

J'ai ajouté ton appli philips sur la branche develop
