### ISSUE TITLE
PowerState sur TV Android

### ISSUE THREAD

**Issue by rouxton** [NextDom/plugin-AndroidRemoteControl#51]
## Description

Apparemment, la plupart des TV Android rentre en deep sleep lorsque mise en veille ce qui veut dire pas de réseau donc pas de retour possible.

## Proposition de solution (optionnel):

Il faudrait intégrer un test réseau (ping ?) pour forcer le mode PowerOff. On pourrait aussi envisager un retour d'info via CEC mais cela suppose une connexion HDMI entre Jeedom et la TV. Ce serait cependant plus propre et permettrait en outre d'allumer la TV (car sinon, même problème, pas de réseau, et surtout pas de WoL sur la plupart des TV). Peut être en option dans la configuration ?

**Comment by byackee** [comment]
Oui nous avons également identifié ce pb sur les TC android, on a testé quelques pistes sas succes pour l'instant. Je vais regarder ta proposition mais pour le moment j'ai d'autres priorités

Merci pour ta participation

**Comment by byackee** [comment]
Il existe des plugins CEC ou WOL qui pourrait etre couplé a AndroidRC via des scénarios.
Je ne pense pas qu'une intégration de ces protocoles soit une bonne chose dans AndroidRC

Pour info des maj ont eu lieu sur les tv philips et les box xiaomi qui ont réglées ces soucis.

**Comment by slobberbone** [comment]
Pour information, sur certaines TV Android Sony, les WOL, et autres outils comme adb étaient mis en "pause" et donc ne répondaient plus une fois la TV en veille depuis un moment. Il semble que ça ne soit plus le cas sur la dernière MAJ de ma Sony ...
