### ISSUE TITLE
Débogage USB... 

### ISSUE THREAD

**Issue by brunoloison** [NextDom/plugin-AndroidRemoteControl#60]
## Description
Bonjour,
merci pour ce plugin qui a l'air vraiment cool.
Pour ma part, ma TV (TCL Xess 2 sous Android TV 6.0) ne me demande pas de valider la connexion de mon raspi (dernière étape de la connexion à la TV).
J'ai bien mis la bonne IP, et la TV répond bien au ping, mais le plugin du coup ne communique pas avec la Télé, et j'ai le petit droid qui boude...

Je sèche.

MERCIIII

## Environnement:

* **Version Jeedom**:   3.2.7
* **Plateforme**:  RPi 3
* **Version du Plugin**:  0.9.6

**Comment by brunoloison** [comment]
Re...

Je viens de voir ça dans le log:
AndroidRemoteControl dependency not found : /usr/bin/adb

J'ai donc relancé l'installation du plugin, et hop, ça fonctionne.

J'adore. 
UN TRES GROS MERCI

**Comment by slobberbone** [comment]
de rien ;)
