### ISSUE TITLE
Les commandes de type action ne fonctionnent pas

### ISSUE THREAD

**Issue by Cerafin** [NextDom/plugin-AndroidRemoteControl#61]
## Description
Les commandes de type info fonctionnent bien mais pas celle de type action, j'obtiens "500 internal server error" et voici ce que j'ai dans les logs http : 

`[Fri May 25 19:54:16.037525 2018] [:error] [pid 796] [client 192.168.1.4:4641] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to AndroidRemoteControlCmd::execute() must be of the type array, null given, called in /var/www/html/core/class/cmd.class.php on line 947 and defined in /var/www/html/plugins/AndroidRemoteControl/core/class/AndroidRemoteControl.class.php:329
Stack trace:
#0 /var/www/html/core/class/cmd.class.php(947): AndroidRemoteControlCmd->execute(NULL)
#1 /var/www/html/core/ajax/cmd.ajax.php(74): cmd->execCmd(NULL)
#2 {main}
thrown in /var/www/html/plugins/AndroidRemoteControl/core/class/AndroidRemoteControl.class.php on line 329, referer: http://192.168.1.19/index.php?v=d&m=AndroidRemoteControl&p=AndroidRemoteControl`

## Environnement:

* **Version Jeedom**: 3.2.7
* **Plateforme**: Debian 9
* **Version du Plugin**: 0.9.7

**Comment by byackee** [comment]
Bonjour,

As tu toujours ce problème ? install la derniere version develop car j'ai corrigé quelques trucs
