### ISSUE TITLE
Message récurent sur cron_execution

### ISSUE THREAD

**Issue by scotty92fr** [NextDom/plugin-AndroidRemoteControl#77]
## Description
Bonjour,

j'ai en permanence le message :
PHP Warning:  Declaration of AndroidRemoteControlCmd::execute(array $_options = Array) should be compatible with cmd::execute($_options = Array) in /var/www/html/plugins/AndroidRemoteControl/core/class/AndroidRemoteControl.class.php on line 396

## Etapes à reproduire (pour les bugs)
N/A ceci est permanent

## Environnement:
* **Version Jeedom**:
3.2.11
* **Plateforme**:
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
Raspbian Linux jeedom 4.14.61-v7+ #1132 SMP Tue Aug 7 15:36:25 BST 2018 armv7l
* **Version du Plugin**:
2018-06-03 07:00:03

**Comment by ColonelMoutarde** [comment]
Salut, est tu en php 7.1 ?

**Comment by scotty92fr** [comment]
non a priori je suis en 7.0.30 :  php -v donne
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by ColonelMoutarde** [comment]
Normalement, c'est bon, peux tu tester ? J'ai fait une mise à jours sur master

**Comment by scotty92fr** [comment]
Désolé pour le délais, je viens de remplacer sur mon installation,  le fichier "AndroidRemoteControl.class.php". je confirme la correction dans la journée.

**Comment by scotty92fr** [comment]
Impeccable, je n'ai plus ces messages. problème résolu.

**Comment by scotty92fr** [comment]
Merci beaucoup
