### ISSUE TITLE
vue de l'activation

### ISSUE THREAD

**Issue by ColonelMoutarde** [NextDom/plugin-AndroidRemoteControl#79]
## Description
décalage de la liste
![screenshot_2018-10-10 plugin - nextdom](https://user-images.githubusercontent.com/4697568/46754862-d213c480-ccc3-11e8-8ae3-c0adc6abbbd4.png)

## Étapes à reproduire (pour les bugs)

1. installer le plugin et se rendre dans le menu d'activation

**Comment by byackee** [comment]
ok
![image](https://user-images.githubusercontent.com/4707496/51484216-32260680-1d9b-11e9-9e1b-0434b9436f71.png)
