### ISSUE TITLE
Ecran noir freebox

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/plugin-AndroidRemoteControl#8]
## Etapes a reproduire (pour les bugs)
1.Connecter le plugin a une freebox mini4k
2.Envoyer un message toast
3.A l'envoi la chain TV freebox se coupe, ecran noir, puis revient avec le message
4.

## Contexte:
Plugin utilisé sur freebox mini4k

## Environnement:
* **Version**: Lollipop
* **Platform**: AndroidTV
* **Subsystem**:

**Comment by byackee** [comment]
Oui effectivement c'est l'apk qui est mal programmé, il faut que je reprenne ca mais ca sera pour la version 1.5 ou 2

**Comment by byackee** [comment]
fonction retirée temporairement
