### ISSUE TITLE
Erreur dans la fonction Cron

### ISSUE THREAD

**Issue by dixnor** [NextDom/plugin-AndroidRemoteControl#83]
## Description
Erreur sur la fonction cron du plugin : Too few arguments to function AndroidRemoteControl::connectADB(), 0 passed in /var/www/html/plugins/AndroidRemoteControl/core/class/AndroidRemoteControl.class.php on line 336 and exactly 1 expected
## Etapes à reproduire (pour les bugs)
L'erreur se produit d'elle même sans aucune intervention usager. 
## Environnement:
Jeedom DIY
* **Version Jeedom**:

3.3.7
* **Plateforme**:
* **Version du Plugin**:

**Comment by byackee** [comment]
Fix with new develop version https://github.com/NextDom/plugin-AndroidRemoteControl/commit/ddea48bca4cde4df169f7397f01afd724c40f9cb

Can you upgrade the plugin and check if is good ?

**Comment by dixnor** [comment]
Everything seems good, problem fixed,
Thanks
