### ISSUE TITLE
Erreur d'affichage sur NextDom

### ISSUE THREAD

**Issue by nam-edi** [NextDom/plugin-AndroidRemoteControl#84]
## Description
Après avoir ajouter l'équipement AndroidRC, quand je me rend sur le dashboard, une partir des fonctionnalités n'est pas visible et/ou cliquable

## Etapes à reproduire (pour les bugs)

1. Créer un equipement Android RC
2. Aller sur le dashboard

* **Version Nextdom**: Version 3.3.7
* **Version du Plugin**: 0.9.9

**Comment by byackee** [comment]
fix with https://github.com/NextDom/plugin-AndroidRemoteControl/commit/9e94a47dd6c7ef45fbe4201f0a5a79b6ed8ad75b
