### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/plugin-AndroidRemoteControl#9]
Options à ajouter :

- Affichage bouton Chaines desactivable (netflix, plex etc..)
- Affichage droid desactivable
- Affichage info desactivable (Resolution etc)

**Comment by cyrilphoenix71** [comment]
- Chaines sur seconde ligne

**Comment by byackee** [comment]
Le template est encour de dev par @slobberbone 
Je regarde pour les options desactivable mais je plug l'issue sur la prochaine version

**Comment by byackee** [comment]
fait
