### ISSUE TITLE
données "title / disk free / disk total" incohérentes sur device nVidia Shield

### ISSUE THREAD

**Issue by zeddiculus** [NextDom/plugin-AndroidRemoteControl#92]
## Description
1. les données "title,diskfree,disktotal" remontent des valeurs incohérentes à cause des 'cut' mal placés dans les commandes adb du fichier AndroidRemoteControl.class.php sur une Shield (première version - uptodate: version Android: 7.2.2).
2. Depuis l'application Amazonvideo, il n'y a pas de valeur dans title, je n'ai pas trouvé de valeur correspondant au média lu dans la commande "adb shell dumpsys bluetooth_manager", j’imagine que l'application ne partage pas cette info de la même manière. Des pistes pour trouver l'info ailleurs?

## Etapes à reproduire (pour les bugs)

1. device SHIELD (première version)
2. Installer/configurer le plugin

## Proposition de solution (optionnel):

Pour les données invalides; modification sur le fichier AndroidRemoteControl.class.php pour remplacer les filtres impactés (a voir si ça ne génère pas de régressions sur d'autres devices?)

        $disk_free = substr($this->runcmd("shell dumpsys diskstats | grep Data-Free | cut -d' ' -f7"), 0, -1);
      log::add('AndroidRemoteControl', 'debug', "disk_free: " .$disk_free );
        $disk_total = round(substr($this->runcmd("shell dumpsys diskstats | grep Data-Free | cut -d' ' -f4"), 0, -1)/1000000, 1);
      log::add('AndroidRemoteControl', 'debug', "disk_total: " .$disk_total);
        $title        = substr($this->runcmd("shell dumpsys bluetooth_manager | grep MediaPlayerInfo |cut -d')' -f3 | cut -d, -f1 | grep -v null"), 0, -2);
      log::add('AndroidRemoteControl', 'debug', "title: " .$title);

Pour la partie Amazonvideo je cherche encore comment récupérer l'info title

## Environnement:

* **Version Jeedom**: 3.2.12
* **Plateforme**: VM debian 8
* **Version du Plugin**: dernière version: ee131c3881ebb9d31b060b21680027735618f755

**Comment by byackee** [comment]
Merci beaucoup pour ce retour, je fais des tests avec ta proposition.

**Comment by zeddiculus** [comment]
Ok, merci!
Pour le title, ma modif n'est pas bonne, si on lance un media sur une app, puis un second ailleurs, les 2 titres s'affichaient. J'ai ajouté un grep sur la variable "encours" pour être sur d'avoir le titre de l'application en premier plan:
$title        = substr($this->runcmd("shell dumpsys bluetooth_manager | grep MediaPlayerInfo | grep .$encours. |cut -d')' -f3 | cut -d, -f1 | grep -v null | sed 's/^\ *//g'"), 0);

(et j'ai ajouté un sed pour virer l'espace au début de la ligne ainsi que le lenght du substr car il retirait des caractères au titre)

Pour amazonvideo, je suis le seul à ne pas avoir de titre (lié au device donc), ou c'est tout le monde?

**Comment by byackee** [comment]
Je n'ai pas testé avec amazon mais il y a d'autres app où cette info n'est pas partagée (molotov je crois). Ca fonctionne bien avec spotify et youtube par exemple.

**Comment by zeddiculus** [comment]
Oui effectivement, youtube et plex pour moi sont OK, molotov aussi d'ailleurs (peut être uniquement avec ma modif? - Pas testé avant)
Par contre rien sur AmazonVideo ou Netflix. 
(Je viens d'envoyer un message au service client d'Amazonvideo, pour leur demander comment récupérer ce genre d'info - L'espoir fait vivre... On verra ou ça va me mener ;) )

**Comment by byackee** [comment]
J'ai mis a jour la version develop avec tes modifications. Sur la shield en version 8.0 ça fonctionne nickel.
