### ISSUE TITLE
Ajouter stbemu a la liste des applications

### ISSUE THREAD

**Issue by arnoakavdb** [NextDom/plugin-AndroidRemoteControl#93]
Bonjour,est ce possible d'ajouter stbemu a la liste des applications a lancer depuis le plugin?merci

**Comment by byackee** [comment]
Salut,

Oui bien-sûr, je ferais ça la semaine prochaine car je suis en vacances 😋

**Comment by slobberbone** [comment]
Euh elle doit déjà y être !

		"name": "stb.emu",
		"icon": "television.png",
      	"type": "action",
    	"subtype": "other",
		"categorie": "appli",
    	"commande": "shell monkey -p com.mvas.stb.emu.pro -c android.intent.category.LAUNCHER 1"

**Comment by byackee** [comment]
je cloture, si pb réouvre une issue mais stb est dans la liste
