### ISSUE TITLE
Volume toujours indiqué à la meme valeur

### ISSUE THREAD

**Issue by ikariya69** [NextDom/plugin-AndroidRemoteControl#95]
## Description

Le retour de la commande "volume" renvoie toujours la même valeur
Mibox 3 sous android 8.0.0

## Etapes à reproduire (pour les bugs)

1. Lancer la commande Volume
2. Le resultat est toujours 14
3.L'envoi de la commande Mute fonctionne
4.Mais la valeur de volume reste indiquée à 14
5. envoie des commandes Volume+ et Volume- Fonctionnent
6. Mais la valeur de volume reste indiquée à 14

## Contexte:

Automatisation de commandes sur mibox et pilotage a partir du cube xiaomi. En fonction de l'angle de rotation du cube, augmenter le volume plus ou moins

## Environnement:
Jeddom + Xiaomi mibox 3

* **Version Jeedom**: 3.3.24
* **Plateforme**: Debian
* **Version du Plugin**:4a055b8311943a0d372d78caecdc55723d7ed2bd (develop)
Testé avec la version master mais meme probleme !

**Comment by byackee** [comment]
Hello,

J'ai mis a jour la branche develop, peux tu tester stp ?
